import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { FormEvent } from 'react'
import { getTheme } from '@fluentui/react'
import { TextField, MaskedTextField } from '@fluentui/react/lib-commonjs/TextField'
import { PrimaryButton } from '@fluentui/react/lib-commonjs/Button'

const theme = getTheme();

export default function Login() {
  const elevation = theme.effects.elevation4
  
  let username = '';
  let password = '';

  const loginClicked = () => {
    alert(`username=${username},password=${password}`);
  }

  const handleChange = (event: FormEvent<HTMLInputElement | HTMLTextAreaElement>, newValue?: string) => {
    username = event.currentTarget.value;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form className={styles.card} style={{ boxShadow: elevation }}>
        <TextField label='username' onChange={handleChange} />
        <TextField label='password' type='password' canRevealPassword value={password} />
        <PrimaryButton text='Login' onClick={loginClicked} style={{marginTop: 10}}/>
      </form>
    </div>
  )
}
